### ISSUE TITLE
sms verification not working in with authorization level set to Application

### ISSUE THREAD

**Issue by wizjack** [sinch/sinch-js-rtc#5]
Hi,

Can you help urgently regarding this issue. When authorization set to application, verification initiation ends with error 403: Authorization requirement not met

It works well when authorization set to to public. I'm using Js sdk. 

Will this help ? https://www.sinch.com/using-rest/#applicationsignedrequest . I'm confused though I'm using JS only not rest.

Thanks.

**Comment by magnuslundstedt** [comment]
JS SDK does not support instance signed verification requests, this is because it's unsafe to bundle the application key within a public website. Our recommended approach is to keep the application setting to public and then secure access by responding to our callbacks. 

If you intend to initiate verifications from a server, we recommend using our Node.js modules.
